// All user-facing strings in one place for future i18n
export const strings = {
  appName: "Canadian Hydrometric Data",
  appTagline: "WSC gauge data, historic analysis & flood frequency",
  nav: {
    map: "Map",
    about: "About",
  },
  station: {
    overview: "Overview",
    historicData: "Historic Data",
    floodFrequency: "Flood Frequency",
    active: "Active",
    discontinued: "Discontinued",
    regulated: "Regulated",
    natural: "Natural",
    rhbn: "RHBN",
    realTime: "Real-time",
    drainageArea: "Drainage Area",
    datum: "Datum",
    recordLength: "Record Length",
    flow: "Flow",
    level: "Level",
    years: "yr",
    km2: "km²",
  },
  map: {
    search: "Search by station name or number…",
    filters: "Filters",
    showingOf: (n: number, total: number) => `Showing ${n} of ${total} stations`,
    selectStation: "Select a station to view details",
    noResults: "No stations match your filters",
  },
  daily: {
    discharge: "Discharge",
    waterLevel: "Water Level",
    units: { discharge: "m³/s", level: "m" },
    hydrograph: "Daily Mean Hydrograph",
    fdc: "Flow-Duration Curve",
    regime: "Mean Annual Regime",
    annualMean: "Annual Mean Series",
    summaryStats: "Summary Statistics",
    downloadCsv: "Download CSV",
    downloadPng: "Download PNG",
    noData: "No daily data available for this station.",
    loading: "Loading daily data…",
  },
  ffa: {
    title: "Flood Frequency Analysis",
    annualPeaks: "Annual Maximum Peak Series",
    frequencyPlot: "Frequency Plot",
    designFloodTable: "Design Flood Estimates",
    goodnessOfFit: "Goodness of Fit",
    warnings: "Data Quality & Reliability",
    downloadCsv: "Download CSV",
    noData: "No annual peak data available for this station.",
    tooFewYears: "Fewer than 5 years of peak data — frequency analysis not possible.",
    loading: "Running flood frequency analysis…",
    returnPeriod: "Return Period (yr)",
    aep: "AEP",
    bestFit: "Best Fit",
  },
  symbols: {
    E: "Estimated",
    A: "Partial day",
    B: "Ice conditions",
    D: "Dry",
    R: "Revised",
    S: "Sampled",
  } as Record<string, string>,
  footer: {
    attribution:
      "Data: Environment and Climate Change Canada (ECCC) — Water Survey of Canada hydrometric data, distributed under the",
    licence: "ECCC Open Data Licence",
    osm: "Map tiles © OpenStreetMap contributors",
    notEndorsed: "This application is not affiliated with or endorsed by ECCC.",
  },
};
