services:
  - type: web
    name: wscprep
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: /opt/render/project/python/bin/uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: ALLOWED_ORIGINS
        value: https://ws-cprep.vercel.app
