services:
  - type: web
    name: wscprep
    runtime: python
    buildCommand: pip install -r requirements.txt && echo "=== UVICORN PATH ===" && pip show uvicorn && echo "=== PIP BIN ===" && dirname $(which pip)
    startCommand: python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: ALLOWED_ORIGINS
        value: https://ws-cprep.vercel.app
